modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="terminamod"
version="1.2.0"
displayName="TerminaMod"
description='''
Adds Ruby to Minecraft.
'''

[[dependencies.terminamod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.terminamod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.terminamod]]
modId="terrablender"
mandatory=true
versionRange="[1.20.1-3.0.1.7,)"
ordering="AFTER"
side="BOTH"